/** Original sector data for Ashlane. Mechanics rhyme with beacon-roguelikes; names, text, and numbers are original. */

export const DESIGN_W = 260;
export const DESIGN_H = 200;

export const ROOMS = [
  { id: "engines", system: "engines", x: 16, y: 52, w: 52, h: 100, maxHp: 8, doors: ["medbay", "oxygen"] },
  { id: "helm", system: "helm", x: 72, y: 16, w: 76, h: 50, maxHp: 6, doors: ["weapons", "medbay"] },
  { id: "weapons", system: "weapons", x: 152, y: 16, w: 92, h: 50, maxHp: 8, doors: ["helm", "shields"] },
  { id: "medbay", system: "medbay", x: 72, y: 70, w: 76, h: 54, maxHp: 8, doors: ["engines", "helm", "shields", "oxygen"] },
  { id: "shields", system: "shields", x: 152, y: 70, w: 92, h: 54, maxHp: 10, doors: ["weapons", "medbay", "cargo"] },
  { id: "oxygen", system: "oxygen", x: 72, y: 128, w: 76, h: 54, maxHp: 7, doors: ["engines", "medbay", "cargo"] },
  { id: "cargo", system: null, x: 152, y: 128, w: 92, h: 54, maxHp: 6, doors: ["shields", "oxygen"] },
];

export const WEAPONS = {
  lance: {
    id: "lance",
    name: "Lance-III",
    kind: "laser",
    power: 1,
    charge: 9,
    shots: 4,
    damage: 1,
    sys: 1,
    stagger: 0.16,
    ammo: 0,
    blurb: "Three pulses. Extra shots peel shields.",
  },
  barb: {
    id: "barb",
    name: "Barb",
    kind: "missile",
    power: 1,
    charge: 11,
    shots: 1,
    damage: 2,
    sys: 2,
    stagger: 0,
    ammo: 1,
    blurb: "Ignores shields. Spends a missile.",
  },
  pike: {
    id: "pike",
    name: "Pike",
    kind: "laser",
    power: 1,
    charge: 9,
    shots: 1,
    damage: 2,
    sys: 2,
    stagger: 0,
    ammo: 0,
    blurb: "One heavy bolt. Hurts once shields drop.",
  },
  tri: {
    id: "tri",
    name: "Triad",
    kind: "laser",
    power: 1,
    charge: 10,
    shots: 3,
    damage: 1,
    sys: 1,
    stagger: 0.18,
    ammo: 0,
    blurb: "Three pulses.",
  },
  pair: {
    id: "pair",
    name: "Pair",
    kind: "laser",
    power: 1,
    charge: 9,
    shots: 2,
    damage: 1,
    sys: 1,
    stagger: 0.2,
    ammo: 0,
    blurb: "Two pulses. Stops cold on two shields.",
  },
  needle: {
    id: "needle",
    name: "Needle",
    kind: "laser",
    power: 1,
    charge: 7.5,
    shots: 1,
    damage: 1,
    sys: 1,
    stagger: 0,
    ammo: 0,
    blurb: "Fast single pulse.",
  },
  ion: {
    id: "ion",
    name: "Ion needle",
    kind: "ion",
    power: 1,
    charge: 7,
    shots: 1,
    damage: 0,
    sys: 0,
    ion: 1,
    stagger: 0,
    ammo: 0,
    blurb: "If it slips a shield, it locks a bubble down.",
  },
};

export const CREW_PRESETS = [
  { id: "ilya", name: "Ilya", room: "helm", color: "#e8a04a" },
  { id: "moss", name: "Moss", room: "weapons", color: "#7ec8e3" },
  { id: "ren", name: "Ren", room: "engines", color: "#c4e07a" },
  { id: "quill", name: "Quill", room: "cargo", color: "#e07ab0" },
];
