export const ENEMIES = {
  skiff: {
    id: "skiff",
    name: "Raider skiff",
    hull: 6,
    reactor: 4,
    missiles: 0,
    crew: 1,
    boarders: 0,
    scrap: [10, 14],
    fuel: [0, 1],
    missileLoot: [0, 1],
    systems: { shields: [0, 0], engines: [1, 2], weapons: [1, 2], oxygen: [1, 1], medbay: [0, 0] },
    weapons: ["needle"],
    roomHp: { shields: 6, weapons: 6, engines: 6 },
  },
  cutter: {
    id: "cutter",
    name: "Lane cutter",
    hull: 8,
    reactor: 5,
    missiles: 0,
    crew: 2,
    boarders: 0,
    scrap: [14, 19],
    fuel: [0, 2],
    missileLoot: [0, 2],
    systems: { shields: [1, 1], engines: [2, 2], weapons: [1, 3], oxygen: [1, 1], medbay: [0, 0] },
    weapons: ["lance"],
    roomHp: { shields: 7, weapons: 7, engines: 6 },
  },
  sloop: {
    id: "sloop",
    name: "Cinder sloop",
    hull: 8,
    reactor: 6,
    missiles: 3,
    crew: 2,
    boarders: 0,
    scrap: [16, 22],
    fuel: [1, 2],
    missileLoot: [1, 2],
    systems: { shields: [1, 2], engines: [2, 3], weapons: [2, 3], oxygen: [1, 1], medbay: [0, 1] },
    weapons: ["needle", "barb"],
    roomHp: { shields: 7, weapons: 8, engines: 6 },
  },
  boarder: {
    id: "boarder",
    name: "Clamp skiff",
    hull: 7,
    reactor: 5,
    missiles: 0,
    crew: 3,
    boarders: 1,
    scrap: [15, 20],
    fuel: [0, 1],
    missileLoot: [0, 2],
    systems: { shields: [1, 1], engines: [1, 2], weapons: [1, 2], oxygen: [1, 1], medbay: [0, 0] },
    weapons: ["needle"],
    roomHp: { shields: 6, weapons: 6, engines: 6 },
  },
  monitor: {
    id: "monitor",
    name: "Ash monitor",
    hull: 11,
    reactor: 7,
    missiles: 1,
    crew: 3,
    boarders: 0,
    scrap: [28, 36],
    fuel: [1, 3],
    missileLoot: [2, 3],
    systems: { shields: [2, 2], engines: [2, 3], weapons: [2, 4], oxygen: [1, 1], medbay: [1, 1] },
    weapons: ["pair", "barb"],
    roomHp: { shields: 8, weapons: 8, engines: 7 },
  },
  warden: {
    id: "warden",
    name: "Reach warden",
    hull: 14,
    reactor: 8,
    missiles: 2,
    crew: 4,
    boarders: 1,
    scrap: [40, 48],
    fuel: [2, 3],
    missileLoot: [2, 4],
    systems: { shields: [1, 2], engines: [2, 3], weapons: [2, 4], oxygen: [1, 1], medbay: [1, 1] },
    weapons: ["tri", "barb"],
    roomHp: { shields: 10, weapons: 9, engines: 8 },
  },
};

